<?php
// $Id$

/**
 * @file
 * Simplifies block administration per role.
 */

define('SIMPLEBLOCKS_DISPLAY_MINIMAL', 1);
define('SIMPLEBLOCKS_DISPLAY_SIMPLE', 2);
define('SIMPLEBLOCKS_DISPLAY_FULL', 3);

/**
 * Implementation of hook_menu().
 */
function simpleblocks_menu() {
  $items = array();

  $items['admin/settings/simpleblocks'] = array(
    'title' => 'Simple Blocks',
    'description' => 'Administer Simple Blocks settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simpleblocks_settings_form'),
    'access arguments' => array('administer simpleblocks settings'),
    'file' => 'simpleblocks.admin.inc',
  );

  $items['admin/user/simpleblocks_permissions'] = array(
    'title' => 'Simple Block Permissions',
    'description' => 'Configure per-block permissions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simpleblocks_permissions_form'),
    'access arguments' => array('administer simpleblocks settings'),
    'file' => 'simpleblocks.admin.inc',
  );

  

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function simpleblocks_perm() {
  return array('administer simpleblocks settings', 'configure blocks', 'configure minimal blocks', 'configure full blocks');
}

/**
 * Check if a user can access the simpleblocks config.
 */
function simpleblocks_user_access($block = NULL)) {
  if (empty($block) {
    $displays = array(
      'configure full blocks' => SIMPLEBLOCKS_DISPLAY_FULL,
      'configure simple blocks' => SIMPLEBLOCKS_DISPLAY_SIMPLE,
      'configure minimal blocks' => SIMPLEBLOCKS_DISPLAY_MINIMAL,  
    );
    foreach ($displays as $perm => $display) {
      if (user_access($perm)) {
        return $display;
      }
    }
    return FALSE;
  }
}

/**
 * Implementation of hook_theme().
 */
function simpleblocks_theme() {
  return array(
    'simpleblocks_permissions_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'simpleblocks.admin.inc',
    ),
  );
}

/**
 * Override or insert variables into the block templates.
 *
 * @param $vars
 *   An array of variables to pass to the theme template.
 * @param $hook
 *   The name of the template being rendered ("block" in this case.)
 */
function simpleblocks_preprocess_block($vars, $hook) {
  $block = $vars['block'];
  if (simpleblocks_user_access($block)) {
    global $user;

    if (theme_get_setting('zen_block_editing') && user_access('administer blocks')) {
      // Unset the zen edit links
      unset($vars['edit_links_array'], $vars['edit_links']);
    }
    $block->content .= _simpleblocks_block_edit_links($block);
  }
}

/**
 * Helper function to create the links that are added to the appropriate block.
 */
function _simpleblocks_block_edit_links($block) {
  return l(t('edit'), 'admin/build/block/configure/' . $block->module . '/' . $block->delta);
}

/**
 * Loads all roles per block (module/delta).
 */
function simpleblocks_roles_load_all() {
  static $roles = array();

  if (empty($roles)) {
    $result = db_query("SELECT * FROM {simpleblocks_roles}");
    while($role = db_fetch_object($result)) {
      $roles[$role->module .'_'. $role->delta][] = $role->rid;
    }
  }

  return $roles;
}

/**
 * Loads all roles per block (module/delta).
 */
function simpleblocks_roles_load($module, $delta) {
  static $roles = array();

  if (empty($roles)) {
    $result = db_query("SELECT * FROM {simpleblocks_roles} WHERE module = '%s' AND delta = '%s'", $module, $delta);
    while($role = db_fetch_object($result)) {
      $roles[] = $role->rid;
    }
  }

  return $roles;
}